import { store } from '@/redux/store'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from '@/lib/Provider'
import MainNavbar from '@/components/MainNavbar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Entertainment Hall',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
     
          <MainNavbar />
          {children}
          <Footer/>
        
    </>
  )
}
