import { store } from '@/redux/store'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from '@/lib/Provider'
import Sidebar from '@/components/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <Providers>
            <html lang="en">
                <body className={inter.className}>
                    <div className='flex '>
                    <div className='w-[20%] p-5'>
                        <Sidebar />
                    </div>
                    <div className='w-[80%] p-5'>

                        {children}
                    </div>
                    </div>
                </body>
            </html>
        </Providers>
    )
}
