import { store } from '@/redux/store'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from '@/lib/Provider'
import Sidebar from '@/components/Sidebar'
import MobileSidebar from '@/components/MobileSidebar'
import DashboardLayout from '@/components/DashboardLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Dashboard Entertainment',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <Providers>
            <html lang="en">
                <body className={inter.className}>
                    <DashboardLayout>{children}</DashboardLayout>
                </body>
            </html>
        </Providers>
    )
}
